### PR TITLE
add local discovery

### PR DESCRIPTION
**Pull request by tangiel**
Several changes are just refactoring. The meat is in the new schema model and the local generator itself.

### CODE REVIEW

**Comment by tangiel** [comment]
@clementdenis Hey Clément, if you have time, can you do some testing on this CL? It's quite a major change.

**Comment by tangiel** [comment]
Pushed an update to fix schema generation for enum fields.

**Comment by clementdenis** [comment]
@tangiel I had a few issues (tested with a version including your latest changes):
- Enum schema generation throws an error when cloning the discovery object in LocalDiscoveryProvider.replaceRoot, because ImmutableLists are used [here](https://github.com/AODocs/endpoints-java/blob/ad7672a958165709bc3483a93debc3667aab923e/endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java#L201).
- Even after fixing this by wrapping enum values and description in mutable Lists, enum methods parameters are gone from the discovery, and the enum schema is missing
- I also have repeated INFO logs about skipping JacksonResourceSchemaProvider.getResourceSchema

```
INFO: skipping field 'classInfo' because it's not a Java client model field.
nov. 10, 2016 1:32:40 PM com.google.api.server.spi.config.jsonwriter.JacksonResourceSchemaProvider getResourceSchema
INFO: skipping field 'factory' because it's not a Java client model field.
nov. 10, 2016 1:32:40 PM com.google.api.server.spi.config.jsonwriter.JacksonResourceSchemaProvider getResourceSchema
INFO: skipping field 'unknownKeys' because it's not a Java client model field.
nov. 10, 2016 1:32:40 PM com.google.api.server.spi.config.jsonwriter.JacksonResourceSchemaProvider getResourceSchema
INFO: skipping field 'empty' because it's not a Java client model field.
```

**Comment by clementdenis** [comment]
Actually, it is a more general problem with method parameters: if a method only contains query parameters, they are not written to the discovery. If there is at least one path parameter, it is OK.
The problem is [here](https://github.com/cloudendpoints/endpoints-java/blob/ad7672a958165709bc3483a93debc3667aab923e/endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java#L170), as only the presence of path parameters is checked.

**Comment by clementdenis** [comment]
[This commit](https://github.com/AODocs/endpoints-java/commit/161ffce0ca66e3d6a79eaa506a4c41ba4369024e) fixes my issues.
Unit tests should be added.

**Comment by tangiel** [comment]
Thanks!

**Comment by tangiel** [comment]
I also changed the logging to fine for the entry you mentioned since it should be normal behavior.

**Pull request merged**
