### PR TITLE
Add documentation link in discovery files

### PR DESCRIPTION
**Pull request by kaldebert**

### CODE REVIEW

**Comment by kaldebert** [comment]
I signed it!

**Comment by kaldebert** [comment]
I signed it!

**Comment by clementdenis** [comment]
Hi @tangiel, is there anything else we should do to have this one merged?
It's actually a regression from Cloud Endpoints v1, documentationLink used to be displayed.
Thanks!

**Comment by tangiel** [comment]
Nope, sorry for missing it. Thanks!

**Pull request merged**
