### PR TITLE
add codecov.io support

### PR DESCRIPTION
**Pull request by tangiel**

### CODE REVIEW

**Comment by tangiel** [comment]
Seems adding the Jacoco plugin broke a lot of tests...looking into it.

**Comment by lookuptable** [comment]
You also need to make gradle check depend on jacocoTestReport, otherwise the jacoco won't be generated by `./gradlew check`

**Comment by tangiel** [comment]
I followed the instructions at https://github.com/codecov/example-gradle instead of changing the gradle task dependency. I don't think gradle check should necessarily depend on it when run by a user, as minor of a difference as it may be.

**Comment by lookuptable** [comment]
LGTM

**Pull request merged**
